services:
  web:
    build: .
    depends_on:
      - mysql
    container_name: serverApache851
    restart: unless-stopped
    ports:
      - "8851:80"
    volumes:
      - ./todolist-app/:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=blog
  mysql:
    image: mariadb
    container_name: serverMySQL851
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3851:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: serverPHPMyAdmin851
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    ports:
      - "7851:80"